[versions]
kotlin = "2.2.21"
kotest = "6.0.3"
ktor = "3.3.3"
coroutines = "1.10.2"

[libraries]
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.9.0" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version = "0.8.2" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.7.1" }
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version = "0.5.0" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version = "7.0.14" }

# networking
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }

# testing
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

kafka-clients = { module = "org.apache.kafka:kafka-clients", version = "4.1.1" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.25" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
testcontainers-kafka = { module = "org.testcontainers:kafka", version = "1.21.3" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
kotest-multiplatform = { id = "io.kotest.multiplatform", version.ref = "kotest" }
mokkery = { id = "dev.mokkery", version = "3.1.1" }
maven-central-publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
